version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/test" # URL для подключения к MongoDB

  mongo:
    image: mongo
    ports:
      - "27017:27017"